//! Experimental js2wasm module backend.
//!
//! js2wasm remains a build-time compiler. At runtime v8x embeds compiler-free
//! Wasmtime, shares one engine plus each precompiled module across isolates,
//! and keeps a private store/instance alive with each owning V8 module handle.
//! The first Deno-shaped host seam is `Deno.cwd()`: the compiled TypeScript
//! wrapper reconstructs its string from two direct UTF-16 imports, avoiding a
//! JavaScript-host `externref` ABI or a WASI/component boundary.

use std::collections::HashMap;
#[cfg(feature = "js2wasm_runtime_compile")]
use std::collections::HashSet;
#[cfg(feature = "js2wasm_runtime_compile")]
use std::fs;
#[cfg(feature = "js2wasm_runtime_compile")]
use std::io::Write;
use std::path::{Path, PathBuf};
#[cfg(feature = "js2wasm_runtime_compile")]
use std::process::Command;
#[cfg(feature = "js2wasm_runtime_compile")]
use std::sync::atomic::AtomicU64;
use std::sync::atomic::{AtomicUsize, Ordering};
use std::sync::{Mutex, OnceLock};
#[cfg(feature = "js2wasm_runtime_compile")]
use std::time::{SystemTime, UNIX_EPOCH};
use wasmtime::{
  Caller, Config, Engine, Instance, InstancePre, Linker, Module, Store,
};

#[cfg(feature = "js2wasm_runtime_compile")]
static NEXT_TEMP_ID: AtomicU64 = AtomicU64::new(0);

const CWD_LENGTH_IMPORT: &str = "__v8x_op_cwd_utf16_length";
const CWD_CODE_UNIT_IMPORT: &str = "__v8x_op_cwd_utf16_code_unit";
const DENO_IMPORT_MODULE: &str = "v8x:deno";
const CWD_LENGTH_PROBE: &str = "__v8x_probe_cwd_utf16_length";
const CWD_CHECKSUM_PROBE: &str = "__v8x_probe_cwd_utf16_checksum";
const DENO_CORE_BOOTSTRAP_PROBE: &str = "__v8x_probe_deno_core_bootstrap";
const DEFERRED_BOOTSTRAP_IMPORTS: &[(&str, &str)] = &[
  ("env", "Promise_new"),
  ("env", "Promise_all"),
  ("env", "Promise_allSettled"),
  ("env", "Promise_any"),
  ("env", "Promise_race"),
  ("js2wasm:runtime-eval", "__runtime_apply_interpreted"),
  ("js2wasm:runtime-eval", "__runtime_indirect_eval"),
];

#[cfg_attr(not(feature = "js2wasm_runtime_compile"), allow(dead_code))]
pub(crate) struct SourceModule {
  pub(crate) specifier: String,
  pub(crate) source: String,
}

struct DenoHostState {
  cwd: Vec<u16>,
  cwd_op_calls: u64,
}

#[derive(Hash, PartialEq, Eq)]
enum ModuleCacheKey {
  TrustedFile(PathBuf),
  #[cfg(feature = "js2wasm_runtime_compile")]
  DevelopmentBytes(Vec<u8>),
}

struct SharedDenoRuntime {
  engine: Engine,
  linker: Linker<DenoHostState>,
  modules: Mutex<HashMap<ModuleCacheKey, InstancePre<DenoHostState>>>,
  module_loads: AtomicUsize,
  instantiations: AtomicUsize,
}

static SHARED_DENO_RUNTIME: OnceLock<Result<SharedDenoRuntime, String>> =
  OnceLock::new();

/// Diagnostic counters exposed only to verify the experimental backend.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Js2WasmRuntimeStats {
  pub cached_modules: usize,
  pub module_loads: usize,
  pub instantiations: usize,
}

impl SharedDenoRuntime {
  fn new() -> Result<Self, String> {
    let mut config = Config::new();
    config
      .wasm_function_references(true)
      .wasm_gc(true)
      .wasm_tail_call(true)
      .wasm_exceptions(true);
    let engine = Engine::new(&config)
      .map_err(|error| format!("configure embedded Wasmtime: {error}"))?;
    let mut linker = Linker::new(&engine);
    linker
      .func_wrap(
        DENO_IMPORT_MODULE,
        CWD_LENGTH_IMPORT,
        |mut caller: Caller<'_, DenoHostState>| -> f64 {
          caller.data_mut().cwd_op_calls += 1;
          caller.data().cwd.len() as f64
        },
      )
      .map_err(|error| format!("bind {CWD_LENGTH_IMPORT}: {error}"))?;
    linker
      .func_wrap(
        DENO_IMPORT_MODULE,
        CWD_CODE_UNIT_IMPORT,
        |mut caller: Caller<'_, DenoHostState>, index: f64| -> f64 {
          caller.data_mut().cwd_op_calls += 1;
          let index = if index.is_finite() && index >= 0.0 {
            index as usize
          } else {
            usize::MAX
          };
          caller.data().cwd.get(index).copied().unwrap_or_default() as f64
        },
      )
      .map_err(|error| format!("bind {CWD_CODE_UNIT_IMPORT}: {error}"))?;
    Ok(Self {
      engine,
      linker,
      modules: Mutex::new(HashMap::new()),
      module_loads: AtomicUsize::new(0),
      instantiations: AtomicUsize::new(0),
    })
  }

  fn precompiled_file(
    &self,
    artifact: &Path,
  ) -> Result<InstancePre<DenoHostState>, String> {
    let artifact = artifact.canonicalize().map_err(|error| {
      format!(
        "resolve precompiled js2wasm artifact {}: {error}",
        artifact.display()
      )
    })?;
    let key = ModuleCacheKey::TrustedFile(artifact.clone());
    let mut modules = self
      .modules
      .lock()
      .map_err(|_| "lock shared js2wasm module cache".to_string())?;
    if let Some(module) = modules.get(&key) {
      return Ok(module.clone());
    }

    // Deployment artifacts are generated by the trusted build pipeline for
    // this exact Wasmtime version/configuration and remain immutable while
    // mapped. Never use this path for user-supplied files.
    let module = unsafe { Module::deserialize_file(&self.engine, &artifact) }
      .map_err(|error| {
      format!(
        "load trusted precompiled js2wasm artifact {}: {error:#}",
        artifact.display()
      )
    })?;
    self.trace_imports(&module);
    let instance_pre = self.instance_pre(&module)?;
    modules.insert(key, instance_pre.clone());
    self.module_loads.fetch_add(1, Ordering::Relaxed);
    Ok(instance_pre)
  }

  #[cfg(feature = "js2wasm_runtime_compile")]
  fn precompile(&self, wasm: &[u8]) -> Result<Vec<u8>, String> {
    self
      .engine
      .precompile_module(wasm)
      .map_err(|error| format!("precompile js2wasm output: {error:#}"))
  }

  #[cfg(feature = "js2wasm_runtime_compile")]
  fn development_bytes(
    &self,
    artifact: &[u8],
  ) -> Result<InstancePre<DenoHostState>, String> {
    let key = ModuleCacheKey::DevelopmentBytes(artifact.to_vec());
    let mut modules = self
      .modules
      .lock()
      .map_err(|_| "lock shared js2wasm module cache".to_string())?;
    if let Some(module) = modules.get(&key) {
      return Ok(module.clone());
    }
    // These bytes were created immediately above by this process's trusted
    // development compiler using the same Engine configuration.
    let module = unsafe { Module::deserialize(&self.engine, artifact) }
      .map_err(|error| {
        format!("load development js2wasm artifact: {error:#}")
      })?;
    self.trace_imports(&module);
    let instance_pre = self.instance_pre(&module)?;
    modules.insert(key, instance_pre.clone());
    self.module_loads.fetch_add(1, Ordering::Relaxed);
    Ok(instance_pre)
  }

  fn trace_imports(&self, module: &Module) {
    if std::env::var_os("V8X_JS2WASM_TRACE_IMPORTS").is_some() {
      for import in module.imports() {
        eprintln!("v8x/js2wasm import {}::{}", import.module(), import.name());
      }
    }
  }

  fn instance_pre(
    &self,
    module: &Module,
  ) -> Result<InstancePre<DenoHostState>, String> {
    for import in module.imports() {
      let known_deno_import = import.module() == DENO_IMPORT_MODULE
        && matches!(import.name(), CWD_LENGTH_IMPORT | CWD_CODE_UNIT_IMPORT);
      let deferred_bootstrap_import = DEFERRED_BOOTSTRAP_IMPORTS
        .iter()
        .any(|candidate| *candidate == (import.module(), import.name()));
      if !known_deno_import && !deferred_bootstrap_import {
        return Err(format!(
          "unimplemented js2wasm host import {}::{}",
          import.module(),
          import.name(),
        ));
      }
    }

    // The exact core bootstrap retains Promise/eval imports as function
    // values, but does not invoke them. Bind only that audited allowlist to
    // Wasmtime's signature-preserving trap functions: boot can instantiate,
    // while the first real use remains an explicit failure rather than a
    // success-shaped default/no-op.
    let mut linker = self.linker.clone();
    linker
      .define_unknown_imports_as_traps(module)
      .map_err(|error| {
        format!("bind deferred js2wasm bootstrap imports: {error:#}")
      })?;
    linker
      .instantiate_pre(module)
      .map_err(|error| format!("resolve js2wasm host imports: {error:#}"))
  }

  fn stats(&self) -> Result<Js2WasmRuntimeStats, String> {
    let modules = self.modules.lock().map_err(|_| {
      "lock shared js2wasm module cache for diagnostics".to_string()
    })?;
    Ok(Js2WasmRuntimeStats {
      cached_modules: modules.len(),
      module_loads: self.module_loads.load(Ordering::Relaxed),
      instantiations: self.instantiations.load(Ordering::Relaxed),
    })
  }
}

fn shared_runtime() -> Result<&'static SharedDenoRuntime, String> {
  SHARED_DENO_RUNTIME
    .get_or_init(SharedDenoRuntime::new)
    .as_ref()
    .map_err(Clone::clone)
}

/// Returns counters for structural sharing tests of the experimental backend.
#[doc(hidden)]
pub fn js2wasm_runtime_stats() -> Result<Js2WasmRuntimeStats, String> {
  shared_runtime()?.stats()
}

/// Diagnostic entry point for the pinned Deno-core bootstrap integration.
#[cfg(feature = "js2wasm_runtime_compile")]
#[doc(hidden)]
pub fn js2wasm_bootstrap_raw_module_for_test(
  artifact: &Path,
) -> Result<(), String> {
  let wasm = fs::read(artifact).map_err(|error| {
    format!(
      "read exact Deno core artifact {}: {error}",
      artifact.display()
    )
  })?;
  let shared = shared_runtime()?;
  let precompiled = shared.precompile(&wasm)?;
  let instance_pre = shared.development_bytes(&precompiled)?;
  let cwd = std::env::current_dir()
    .map_err(|error| format!("resolve test working directory: {error}"))?;
  DenoRuntime::instantiate(shared, &instance_pre, cwd.clone())?;
  DenoRuntime::instantiate(shared, &instance_pre, cwd)?;
  Ok(())
}

/// Instantiate the prelinked core-bootstrap transaction used by the
/// experimental classic-script bridge. Production uses a trusted artifact;
/// development builds may precompile the exact raw module in-process.
pub(crate) fn deno_core_bootstrap_runtime_from_env()
-> Result<DenoRuntime, String> {
  let shared = shared_runtime()?;
  let instance_pre = if let Some(artifact) =
    std::env::var_os("V8X_JS2WASM_DENO_CORE_AOT_MODULE")
  {
    shared.precompiled_file(Path::new(&artifact))?
  } else {
    #[cfg(feature = "js2wasm_runtime_compile")]
    {
      let artifact = std::env::var_os("V8X_JS2WASM_DENO_CORE_WASM")
        .ok_or_else(|| {
          "set V8X_JS2WASM_DENO_CORE_AOT_MODULE to a trusted precompiled artifact (or V8X_JS2WASM_DENO_CORE_WASM in a development build)".to_string()
        })?;
      let wasm = fs::read(&artifact).map_err(|error| {
        format!(
          "read exact Deno core artifact {}: {error}",
          Path::new(&artifact).display()
        )
      })?;
      let precompiled = shared.precompile(&wasm)?;
      shared.development_bytes(&precompiled)?
    }
    #[cfg(not(feature = "js2wasm_runtime_compile"))]
    {
      return Err(
        "compiler-free engine_js2wasm builds require V8X_JS2WASM_DENO_CORE_AOT_MODULE to point to a trusted Wasmtime-precompiled artifact"
          .to_string(),
      );
    }
  };
  let cwd = std::env::current_dir().map_err(|error| {
    format!("resolve Deno bootstrap working directory: {error}")
  })?;
  DenoRuntime::instantiate(shared, &instance_pre, cwd)
}

/// One private Wasmtime store and instance owned by a v8x module handle.
pub(crate) struct DenoRuntime {
  store: Store<DenoHostState>,
  instance: Instance,
}

impl DenoRuntime {
  fn instantiate(
    shared: &SharedDenoRuntime,
    instance_pre: &InstancePre<DenoHostState>,
    cwd: PathBuf,
  ) -> Result<Self, String> {
    let cwd = cwd.to_string_lossy().encode_utf16().collect();
    let mut store = Store::new(
      &shared.engine,
      DenoHostState {
        cwd,
        cwd_op_calls: 0,
      },
    );
    let instance = instance_pre
      .instantiate(&mut store)
      .map_err(|error| format!("instantiate js2wasm artifact: {error}"))?;
    shared.instantiations.fetch_add(1, Ordering::Relaxed);
    let mut runtime = Self { store, instance };
    runtime.run_deferred_module_init()?;
    runtime.verify_cwd_probe()?;
    runtime.verify_deno_core_bootstrap_probe()?;
    Ok(runtime)
  }

  fn run_deferred_module_init(&mut self) -> Result<(), String> {
    let Some(init) = self.instance.get_func(&mut self.store, "__module_init")
    else {
      return Ok(());
    };
    init
      .typed::<(), ()>(&self.store)
      .map_err(|error| format!("type __module_init: {error}"))?
      .call(&mut self.store, ())
      .map_err(|error| format!("run __module_init: {error:#}"))
  }

  fn verify_cwd_probe(&mut self) -> Result<(), String> {
    let Some(length) =
      self.instance.get_func(&mut self.store, CWD_LENGTH_PROBE)
    else {
      return Ok(());
    };
    let checksum = self
      .instance
      .get_func(&mut self.store, CWD_CHECKSUM_PROBE)
      .ok_or_else(|| {
        format!(
          "artifact exports {CWD_LENGTH_PROBE} without {CWD_CHECKSUM_PROBE}"
        )
      })?;
    let length = length
      .typed::<(), f64>(&self.store)
      .map_err(|error| format!("type {CWD_LENGTH_PROBE}: {error}"))?
      .call(&mut self.store, ())
      .map_err(|error| format!("call {CWD_LENGTH_PROBE}: {error}"))?;
    let checksum = checksum
      .typed::<(), f64>(&self.store)
      .map_err(|error| format!("type {CWD_CHECKSUM_PROBE}: {error}"))?
      .call(&mut self.store, ())
      .map_err(|error| format!("call {CWD_CHECKSUM_PROBE}: {error}"))?;
    let expected_length = self.store.data().cwd.len() as f64;
    let expected_checksum = self
      .store
      .data()
      .cwd
      .iter()
      .enumerate()
      .map(|(index, unit)| (index as f64 + 1.0) * f64::from(*unit))
      .sum::<f64>();
    if length != expected_length || checksum != expected_checksum {
      return Err(format!(
        "Deno.cwd() bridge returned length/checksum {length}/{checksum}, expected {expected_length}/{expected_checksum} ({} host calls)",
        self.store.data().cwd_op_calls,
      ));
    }
    let expected_calls = 2 * (self.store.data().cwd.len() as u64 + 1);
    if self.store.data().cwd_op_calls != expected_calls {
      return Err(format!(
        "Deno.cwd() probe made {} typed host calls, expected {expected_calls} for a fresh instance",
        self.store.data().cwd_op_calls,
      ));
    }
    Ok(())
  }

  fn verify_deno_core_bootstrap_probe(&mut self) -> Result<(), String> {
    let Some(probe) = self
      .instance
      .get_func(&mut self.store, DENO_CORE_BOOTSTRAP_PROBE)
    else {
      return Ok(());
    };
    let value = probe
      .typed::<(), f64>(&self.store)
      .map_err(|error| format!("type {DENO_CORE_BOOTSTRAP_PROBE}: {error}"))?
      .call(&mut self.store, ())
      .map_err(|error| {
        format!("call {DENO_CORE_BOOTSTRAP_PROBE}: {error:#}")
      })?;
    if value != 42.0 {
      return Err(format!(
        "Deno core bootstrap probe returned {value}, expected 42"
      ));
    }
    Ok(())
  }
}

pub(crate) fn compile_and_instantiate(
  entry: &str,
  modules: &[SourceModule],
) -> Result<DenoRuntime, String> {
  if modules.is_empty() {
    return Err("js2wasm module graph is empty".to_string());
  }
  let shared = shared_runtime()?;
  let instance_pre = if let Some(artifact) =
    std::env::var_os("V8X_JS2WASM_AOT_MODULE")
  {
    shared.precompiled_file(Path::new(&artifact))?
  } else {
    #[cfg(feature = "js2wasm_runtime_compile")]
    {
      let wasm = compile_graph(entry, modules)?;
      let artifact = shared.precompile(&wasm)?;
      if let Some(output) = std::env::var_os("V8X_JS2WASM_ARTIFACT_OUTPUT") {
        fs::write(&output, &artifact).map_err(|error| {
          format!(
            "write precompiled js2wasm artifact {}: {error}",
            Path::new(&output).display()
          )
        })?;
      }
      shared.development_bytes(&artifact)?
    }
    #[cfg(not(feature = "js2wasm_runtime_compile"))]
    {
      let _ = (entry, modules);
      return Err(
          "compiler-free engine_js2wasm builds require V8X_JS2WASM_AOT_MODULE to point to a trusted Wasmtime-precompiled artifact"
            .to_string(),
        );
    }
  };
  let cwd = std::env::current_dir()
    .map_err(|error| format!("resolve Deno.cwd() host value: {error}"))?;
  DenoRuntime::instantiate(shared, &instance_pre, cwd)
}

#[cfg(feature = "js2wasm_runtime_compile")]
fn compile_graph(
  entry: &str,
  modules: &[SourceModule],
) -> Result<Vec<u8>, String> {
  let temp = TempDir::new()?;
  let manifest_path = temp.path.join("modules.tsv");
  let wasm_path = temp.path.join("module.wasm");
  let mut manifest = fs::File::create(&manifest_path)
    .map_err(|error| format!("create js2wasm manifest: {error}"))?;

  let mut seen = HashSet::new();
  for (index, module) in modules.iter().enumerate() {
    if module.specifier.contains(['\t', '\n', '\r']) {
      return Err(format!(
        "js2wasm spike cannot encode module specifier {:?}",
        module.specifier
      ));
    }
    if !seen.insert(module.specifier.as_str()) {
      continue;
    }
    let source_path = temp.path.join(format!("source-{index}.ts"));
    fs::write(&source_path, &module.source)
      .map_err(|error| format!("write js2wasm source: {error}"))?;
    writeln!(manifest, "{}\t{}", module.specifier, source_path.display())
      .map_err(|error| format!("write js2wasm manifest: {error}"))?;
  }
  drop(manifest);

  let script =
    std::env::var_os("V8X_JS2WASM_COMPILER_SCRIPT").ok_or_else(|| {
      "V8X_JS2WASM_COMPILER_SCRIPT must point to compile-graph.ts (or set V8X_JS2WASM_AOT_MODULE)".to_string()
    })?;
  let compiler =
    std::env::var_os("V8X_JS2WASM_COMPILER").unwrap_or_else(|| "node".into());
  let mut compile = Command::new(&compiler);
  if Path::new(&compiler)
    .file_name()
    .is_some_and(|name| name == "node")
  {
    compile.args(["--import", "tsx"]);
  }
  compile
    .arg(script)
    .arg("--manifest")
    .arg(&manifest_path)
    .arg("--entry")
    .arg(entry)
    .arg("--output")
    .arg(&wasm_path);
  if let Some(workdir) = std::env::var_os("V8X_JS2WASM_WORKDIR") {
    compile.current_dir(workdir);
  }
  run(compile, "js2wasm compilation")?;
  fs::read(&wasm_path)
    .map_err(|error| format!("read compiled js2wasm artifact: {error}"))
}

#[cfg(feature = "js2wasm_runtime_compile")]
fn run(mut command: Command, phase: &str) -> Result<(), String> {
  let output = command
    .output()
    .map_err(|error| format!("start {phase}: {error}"))?;
  if output.status.success() {
    return Ok(());
  }

  let stderr = String::from_utf8_lossy(&output.stderr);
  let stdout = String::from_utf8_lossy(&output.stdout);
  let detail = if !stderr.trim().is_empty() {
    stderr.trim()
  } else if !stdout.trim().is_empty() {
    stdout.trim()
  } else {
    "process exited without output"
  };
  Err(format!("{phase} failed: {detail}"))
}

#[cfg(feature = "js2wasm_runtime_compile")]
struct TempDir {
  path: PathBuf,
}

#[cfg(feature = "js2wasm_runtime_compile")]
impl TempDir {
  fn new() -> Result<Self, String> {
    let timestamp = SystemTime::now()
      .duration_since(UNIX_EPOCH)
      .unwrap_or_default()
      .as_nanos();
    let id = NEXT_TEMP_ID.fetch_add(1, Ordering::Relaxed);
    let path = std::env::temp_dir().join(format!(
      "v8x-js2wasm-{}-{timestamp}-{id}",
      std::process::id()
    ));
    fs::create_dir(&path)
      .map_err(|error| format!("create js2wasm temp directory: {error}"))?;
    Ok(Self { path })
  }
}

#[cfg(feature = "js2wasm_runtime_compile")]
impl Drop for TempDir {
  fn drop(&mut self) {
    let _ = fs::remove_dir_all(&self.path);
  }
}
